import { Link } from 'react-router-dom';
import { Info, HelpCircle, Shield, FileText } from 'lucide-react';

const sections = [
  { id: 'about', label: 'About', icon: Info },
  { id: 'faq', label: 'FAQs', icon: HelpCircle },
  { id: 'privacy', label: 'Privacy Policy', icon: Shield },
  { id: 'terms', label: 'Terms of Service', icon: FileText },
];

const faqs = [
  {
    q: 'How does Sirius Jobs work?',
    a: 'Post what you need done, compare bids or quotes from taskers and professionals near you, and pay securely once the work is agreed. Small tasks use secure in-app payment held until you confirm the job is done; bigger trade jobs connect you directly with a professional to arrange and pay for the work yourselves.',
  },
  {
    q: "What's the difference between a task and a lead?",
    a: 'Small, everyday jobs (cleaning, errands, small repairs) go through bidding with payment held securely until you confirm completion. Bigger trade jobs (plumbing, electrical, building work) work differently — a professional pays a small fee to get your contact details and reaches out to quote and arrange the job directly with you.',
  },
  {
    q: 'Is my payment safe?',
    a: "For small tasks, yes — your payment is held securely and only released to the tasker once you've confirmed the job is done. For trade jobs matched through the lead system, payment happens directly between you and the professional, the same way it would if you found them any other way.",
  },
  {
    q: 'How do I become a verified tasker or professional?',
    a: "From your account Settings, submit your NIN and a photo of your ID along with a small one-time fee. Once our team reviews and approves it, a Verified Badge appears on your profile, signaling to posters that your identity has been checked.",
  },
  {
    q: 'What if something goes wrong with a task?',
    a: "Reach out through the in-app chat with the other party first. If that doesn't resolve it, either side can raise a dispute on the task while it's still in progress, and our team will review it and decide how the payment held in escrow should be handled.",
  },
];

export default function About() {
  return (
    <section className="px-4 py-12 lg:px-8">
      <div className="mx-auto max-w-3xl">
        <nav className="mb-10 flex flex-wrap gap-2">
          {sections.map(({ id, label, icon: Icon }) => (
            <a
              key={id}
              href={`#${id}`}
              className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-4 py-2 text-sm font-semibold text-gray-600 transition-colors hover:border-primary hover:text-primary"
            >
              <Icon className="h-3.5 w-3.5" />
              {label}
            </a>
          ))}
        </nav>

        <section id="about" className="scroll-mt-24">
          <h1 className="text-3xl font-black text-gray-900">About Sirius Jobs</h1>
          <div className="prose prose-gray mt-4 max-w-none text-gray-700">
            <p>
              Sirius Jobs is a Nigerian task marketplace connecting people who need work
              done with trusted taskers and professionals nearby. Post a quick errand or a
              major trade job, compare bids or quotes, and get it handled — with secure
              payment for small tasks and direct connections for bigger trade work.
            </p>
            <p className="mt-4">
              We're built for how Nigerians actually work: fast, local, and trust-first.
              Whether it's a leaking pipe that needs a quick fix or a full bathroom
              renovation, Sirius Jobs helps you find the right person for the job.
            </p>
          </div>
        </section>

        <section id="faq" className="mt-16 scroll-mt-24">
          <h2 className="text-2xl font-black text-gray-900">Frequently Asked Questions</h2>
          <div className="mt-6 space-y-4">
            {faqs.map((faq) => (
              <div
                key={faq.q}
                className="rounded-2xl border border-gray-200/70 bg-white p-6 shadow-sm"
              >
                <h3 className="font-bold text-gray-900">{faq.q}</h3>
                <p className="mt-2 text-sm leading-relaxed text-gray-600">{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        <section id="privacy" className="mt-16 scroll-mt-24">
          <h2 className="text-2xl font-black text-gray-900">Privacy Policy</h2>
          <div className="prose prose-gray mt-4 max-w-none space-y-4 text-sm leading-relaxed text-gray-600">
            <p>
              We collect the information you give us when you create an account (name,
              email, phone number, city) and information generated by using the platform
              (tasks posted, bids made, messages, reviews). If you apply for a Verified
              Badge, we collect your NIN and a government ID for verification purposes
              only.
            </p>
            <p>
              We use this information to operate the platform — matching tasks with
              taskers, processing payments through our payment partner (Paystack), showing
              your public profile (name, rating, completion count) to other users, and
              communicating with you about your account or tasks.
            </p>
            <p>
              We do not sell your personal information. We share data with service
              providers only as needed to run the platform (e.g. Paystack for payments,
              Supabase for hosting our database). Payment card details are handled
              entirely by Paystack — Sirius Jobs never stores your card information.
            </p>
            <p>
              You can request a copy of your data or ask us to delete your account by
              contacting us at the email address in the footer. This policy may be updated
              as the platform evolves; significant changes will be communicated to users.
            </p>
          </div>
        </section>

        <section id="terms" className="mt-16 scroll-mt-24 pb-16">
          <h2 className="text-2xl font-black text-gray-900">Terms of Service</h2>
          <div className="prose prose-gray mt-4 max-w-none space-y-4 text-sm leading-relaxed text-gray-600">
            <p>
              By using Sirius Jobs, you agree to use the platform honestly and lawfully —
              accurate task descriptions, fair bids, and respectful communication with
              other users.
            </p>
            <p>
              For small tasks posted through the bidding path, payment is held securely
              and released to the tasker once the poster confirms the task is complete.
              Sirius Jobs takes a service fee from this payment, communicated before you
              accept a bid.
            </p>
            <p>
              For trade jobs posted through the lead-matching path, Sirius Jobs charges
              professionals a fee to connect with your task. The work itself, its
              pricing, and payment are agreed directly between you and the professional —
              Sirius Jobs is not a party to that agreement and does not guarantee the
              outcome of off-platform arrangements.
            </p>
            <p>
              Users are responsible for the accuracy of information on their profile and
              for any work they agree to perform or commission. Sirius Jobs may suspend
              accounts that violate these terms, post fraudulent tasks, or attempt to
              circumvent platform fees through repeated off-platform arrangements on
              tasks that should go through escrow.
            </p>
            <p>
              These terms may be updated as Sirius Jobs grows. Continued use of the
              platform after changes means you accept the updated terms.
            </p>
          </div>
        </section>

        <div className="border-t border-gray-200 pt-8 text-center">
          <p className="text-sm text-gray-500">
            Questions we haven't covered?{' '}
            <a
              href="mailto:info@siriusjobs.com.ng"
              className="font-semibold text-primary hover:underline"
            >
              info@siriusjobs.com.ng
            </a>
          </p>
          <Link
            to="/"
            className="mt-4 inline-block text-sm font-semibold text-gray-600 hover:text-primary"
          >
            ← Back to home
          </Link>
        </div>
      </div>
    </section>
  );
}
